### ISSUE TITLE
Support Regenie output format from pheweb

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#167]
How about making a little bit change to support Regenie output? Here is the header of regenie 2.2.2 output

```
CHROM GENPOS ID ALLELE0 ALLELE1 A1FREQ N TEST BETA SE CHISQ LOG10P EXTRA
6 137601 chr6_137601_A_AT A AT 4.68441e-05 106737 REC -0.442561 0.668763 0.437927 0.29403 NA
6 148040 chr6_148040_G_A G A 0.0277789 102002 REC -0.0248262 0.0679383 0.133534 0.145818 NA
6 148162 chr6_148162_G_A G A 0.0338301 101448 REC -0.0468085 0.06469 0.523569 0.328528 NA
6 148172 chr6_148172_G_A G A 0.0241675 102969 REC -0.00743771 0.084952 0.00766534 0.0314083 NA
6 148194 chr6_148194_TGC_T TGC T 0.0362142 108949 REC -0.0817697 0.0565592 2.09015 0.829002 NA
6 148277 chr6_148277_C_T C T 0.00861931 105867 REC 0.102096 0.236454 0.186436 0.176591 NA
6 148508 chr6_148508_C_CA C CA 0.746834 109588 REC -0.00111166 0.00406664 0.0747257 0.105365 NA
6 148535 chr6_148535_C_T C T 0.00827016 108039 REC 0.102743 0.236453 0.188804 0.177888 NA
```

**Comment by pjvandehaar** [comment]
This change will need some work to know how to import either pval or log10pval.

**Comment by hoogla** [comment]
Hi Peter and PheWeb team, 
are there any updates on this topic? Having the option to directly import Regenie output files without having to create some temporary intermediate files with pval instead of log10pval would be great. 
If this is not planned, would it be possible to point me to the part of the PheWeb code where I might add a little something myself, or are the changes in too many places?
Thanks and best,
Hagen

**Comment by pjvandehaar** [comment]
This is supported now.
