### ISSUE TITLE
PheWeb can display phenotype correlations generated by another tool. 

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#218]
Hi, guys:

The Github main page says that 
**PheWeb can display phenotype correlations generated by [another tool](https://github.com/statgen/pheweb-rg-pipeline).**. I think it actually means "**display genetic correlations**", since the first sentence on the **pheweb-rg-pipeline** Github page says: **Pipeline for calculating genetic correlations via summary statistics between >1,000 phenotypes in PheWeb**.

Taking **[pheweb.jp](https://pheweb.jp/phenotypes)** for example, shown as below, I wonder how genetic correlation could be displayed for the first 6 traits, since there is no check-box at all. 

![image](https://github.com/statgen/pheweb/assets/26947455/1edf49dc-3ed3-4cf9-a323-bd15259b602e)

Please let me know.

Thank you very much & best regards,
Jie

**Comment by sgagliano** [comment]
Thanks for catching this error in the README. It has now been corrected.

**Comment by jielab** [comment]
So, can pheweb display "genetic correlation" **across traits**? Say that I have 10 GWAS in Pheweb, can I display the genetic correlation (r2) for the **10*10** pairs?

I am following the instruction to install **nextflow**. When I run the following code,  I got the error message: **CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: false (for stack trace, run with -Dcapsule.log=verbose).**
`curl -s https://get.nextflow.io | bash`

Best regards,
Jie

**Comment by sgagliano** [comment]
Hello. Yes, PheWeb can display pairwise genetic correlations across all traits loaded in the instance of PheWeb if the genetic correlation output (e.g. from pairwise LDSC, for instance), is provided. 
For instance, we have added pairwise genetic correlations to the instance of PheWeb displaying UK Biobank PheCodes (using the HRC-imputed dataset). Let's take "Type 1 diabetes" as an example: https://pheweb.org/UKB-SAIGE/pheno/250.1. If you scroll down, below the QQ plot, you will see a table displaying the genetic correlations between Type 1 diabetes and other traits in this instance of PheWeb. Note that in this instance of PheWeb, because we conducted pairwise genetic correlations on a large amount of traits (n = 1400), we only display pairs of traits with a genetic correlation p-value < 0.05 for efficiency. If the genetic correlation table is blank (e.g. for the trait "Disorders of iron metabolism"; https://pheweb.org/UKB-SAIGE/pheno/275.1), it means that there were no pairwise genetic correlations between that trait and any other trait in the instance of PheWeb with p < 0.05.

**Comment by jielab** [comment]
It is great that pheweb could indeed display rg for many traits!

Please see the two screenshots below, I now successfully installed **LDSC** and **NEXTFLOW**. Both are installed through **conda**. Somehow I need to **conda activate ldsc**, while I do NOT need to "conda activate nextflow". However, once I run **conda activate ldsc**, the **nextflow** executable is NOT executable any more ...  As you know, LDSC is built in python 2, while my default python is python 3. So, I have to run **conda activate ldsc** first in order to run **ldsc**.

![image](https://github.com/statgen/pheweb/assets/26947455/6cf18274-4185-4019-970f-1445628f4021)

![image](https://github.com/statgen/pheweb/assets/26947455/18af5250-e954-4013-bdc9-d78bb8afcd88)

I could not follow the following instruction either "**_Before running the pipeline you may need to change your LDSC/nextflow.config file_**", since I have no idea where the **LDSC/nextflow.config** file is supposed to be.

So, can you guys please update the https://github.com/statgen/pheweb-rg-pipeline with a little bit more details so that users could follow it step-by-step? The pheweb pipeline is great. Users like me could follow it head-to-toe. 

Thank you very much & best regards,
Jie
