### ISSUE TITLE
Understand why a field|transform must be in .fields to work (even in phewas)

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#60]
(how did I lose them?)

At <http://statgen.github.io/locuszoom/examples/phewas_scatter.html>, labels are configured in `layout.panels[0].data_layers[1].label.filters` is `[{"field":"pval|neglog10","operator":">=","value":5}]`.

On <http://pheweb.sph.umich.edu:5000/variant/11-5248004-G-A>, `window.debug.phewas_panel.data_layers[1].label.filters` is `[{"field":"pval|neglog10","operator":">=","value":3.380211241711606}]`.

Why is that coming out false?

**Comment by pjvandehaar** [comment]
Ah, I can only use `pval|neglog10` if it's in `.fields`.  I should figure out why that is.

**Comment by Frencil** [comment]
This was likely because the new LocusZoom.Data.Fields impementation is only partial. Just about everywhere in data layers the old approach for resolving fields (looking for exact matches on the data object) are used.

See [this commit](https://github.com/statgen/locuszoom/commit/bb9eb9607e2d5c952ede16da7ecab9085bdfced0) on master that ports the data filtering piece on labels to use the new stuff, which is capable of deferring transformations. This *should* address this problem (or if it doesn't something that looks a lot like that but elsewhere in the label code should do the trick).

Ultimately *most* places should be resolving field values through the `LocusZoom.Data.Fields` object, but I'd be hesitant to say all of them should.
